### PR TITLE
bug/fix-hexlet-check

### PR DESCRIPTION
**Pull request by alex-popov-tech**

### CODE REVIEW

**Comment by alex-popov-tech** [comment]
@foofaev can you assist on error from hexlet check?

**Comment by foofaev** [comment]
It tries to read main field in your package.json file and cannot find it
check https://github.com/hexlet-boilerplates/fastify-nodejs-application/blob/55aed1e99cae01f4346adb1fd4de746914f6099f/package.json#L5

**Comment by alex-popov-tech** [comment]
thanks, now there is one more issue, can you please take a look?

**Comment by foofaev** [comment]
Knexfile -> path.resolve builds invalid path if called from outside folder

**Pull request merged**
